// <auto-generated />
using System;
using AttendanceRollApp.LocalDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceRollApp.LocalDBContext.Migrations
{
    [DbContext(typeof(AttrollDBContext))]
    [Migration("20231122194234_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AttendanceRollApp.SharedUI.Models.Attendance", b =>
                {
                    b.Property<int>("dbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthMethoddbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTimeSynced")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonNationalID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("dbId");

                    b.HasIndex("AuthMethoddbId");

                    b.HasIndex("PersonNationalID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("AttendanceRollApp.SharedUI.Models.Attendance+AuthenticationMethod", b =>
                {
                    b.Property<int>("dbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("dbId");

                    b.ToTable("AuthenticationMethod");
                });

            modelBuilder.Entity("AttendanceRollApp.SharedUI.Models.Person", b =>
                {
                    b.Property<string>("NationalID")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfcSerialNumbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NationalID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AttendanceRollApp.SharedUI.Models.Attendance", b =>
                {
                    b.HasOne("AttendanceRollApp.SharedUI.Models.Attendance+AuthenticationMethod", "AuthMethod")
                        .WithMany()
                        .HasForeignKey("AuthMethoddbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceRollApp.SharedUI.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonNationalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthMethod");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
